elliottneilclark/rs-poker

fuzz/Cargo.toml
fuzz/fuzzers/rank_seven.rs

Add on a fuzz script that will validate that the rank_seven method on Rankable will give the same value as rank. Then I ran this for a few hours. Checked the corpus and it all looked really good.
Changed the fuzz default optimization level.

Add on fuzz script to validate rank_seven

---

src/core/rank.rs

Rather than finding the straights by shifting a mask. Shift the values to see if there are 5 ones in a row. Then if there were 5 ones in a row, find out if where they are by finding the location of the leading one.

Find straights by shifting and masking

---

Cargo.lock
Cargo.toml
flake.lock
src/arena/game_state.rs
src/arena/simulation.rs
src/holdem/monte_carlo_game.rs
src/lib.rs
src/utils/mod.rs
src/utils/player_bit_set.rs

We know there aren't that many players at a table. Way below 16 (however sometimes above 8) so we can use a u16 as our storage type. Allowing no heap allocations, and fast bit twidling since we don't have the vec indirection.
- Add on a PlayerBitSet that's useful for keeping track of players doing something at a table.
- Changed arena to use this
- Changed monte carlo game simulation to use this

perf: dont use heap alocated bitsets for player active sets

---

src/arena/errors.rs
src/arena/game_state.rs

Digging into #45 adding a tests to make sure that GameState rejects bad bets that don't call the previous.

test: add a test to ensure bets call in GameState

---

benches/arena.rs
src/arena/agent/random.rs
src/arena/simulation.rs

The order of new with hands and deck was off. Deck was not the last paramter despite being the name.
This is a breaking change, but we already needed one for the replay agent so 3.0.0 is incomming.

fix: upate the simluation paramter ordering to match the name

---

.envrc.example

We don't require nix, but we also don't want to make its usage a mystery. So this adds an example
Test:
This is a copy of the envrc I'm currently using

docs: add an example .envrc

---

fuzz/fuzz_targets/replay_agent.rs
src/arena/agent/random.rs

Give replay agent fuzzing a way to go all in reasonably. 
Make RandomAgent bet somewhat around the pot value.

test: make replay agent fuzzing and RandomAgent closer to reality with bet sizing

---

Cargo.lock
Cargo.toml
src/simulated_icm/mod.rs

We use a u16 for players in a table. So this was the only place still remaining that was using fixed bit set. It didnt' seem worth it to keep for one place.

refactor: remove the FixBitSet depenedency

---

Cargo.lock
benches/arena.rs
flake.lock
fuzz/Cargo.toml
fuzz/fuzz_targets/replay_agent.rs
src/arena/agent/calling.rs
src/arena/agent/folding.rs
src/arena/agent/mod.rs
src/arena/agent/random.rs
src/arena/errors.rs
src/arena/mod.rs
src/arena/simulation.rs
src/core/flat_deck.rs
src/holdem/monte_carlo_game.rs

- Switch to a builder for `HoldemSimulation`
- Add the ability to set the rng
- Use that ability in fuzzing to explore decks

feat: use a builder pattern for holdem simulation

---

fuzz/fuzz_targets/replay_agent.rs
src/arena/action.rs
src/arena/simulation.rs

Summary:
When starting a game theres a lot of game state that we don't get from
actions. This diff will add on more actions such that the sequence of
actions should be able to reconstruct the game state at any time.
Test Plan:
Fuzzed some
This needs better tests

feat: add more action types and more info

---

Cargo.lock
Cargo.toml
flake.lock
flake.nix
fuzz/Cargo.toml
fuzz/fuzz_targets/fuzzer_script_1.rs
fuzz/fuzz_targets/fuzzer_script_2.rs
fuzz/fuzz_targets/multi_replay_agent.rs
fuzz/fuzz_targets/replay_agent.rs
src/arena/action.rs
src/arena/agent/random.rs
src/arena/agent/replay.rs
src/arena/errors.rs
src/arena/game_state.rs
src/arena/simulation.rs
src/arena/test_util.rs
src/core/flat_deck.rs

Summary:
I want to use the multi-agent fuzzing to test the more precise
action log. So this is a first pass at adding that and cleaning up
around it
Then when writing that fuzz we can re-use the test utils everywhere.
That found an issue. We were transitioning the game to complete if an
agent folded. However there was still one player to act in a previous
round. So since we reset counts and data, it allowed invalid actions
This also found another issue: We were not starting on the dealer flop
on.
This also found another issue: The action log was using an incorrect idx
for the player.
Test Plan:
The whole thing is a test

test: add more fuzzing goodness

---

Cargo.lock
Cargo.toml
flake.lock

Summary:
This updates cargo deps for testing, and nix deps for compiler and build
tools.  Preparing for another release
Test Plan:
CI
`nix flake check`

chore(deps): update latest cargo and nix deps

---

benches/arena.rs
src/arena/agent/random.rs
src/arena/game_state.rs

Summary:
Lets let people try and mimic raising less if there's already been some
aggression. To do that keep track of the total number of raises. Then
rather than a static percentage, use a vector of percentages that we
traverse farther into.
So we can fold more when there's been more betting and we can call more
meaning we also bet less.
Test Plan:
Changed the tests, and they still pass

feat: track total_raise_count and use that in random agent

---

Cargo.lock
flake.lock
src/arena/simulation.rs
src/core/card.rs
src/core/card_bit_set.rs
src/core/deck.rs
src/core/mod.rs
src/holdem/monte_carlo_game.rs

Summary:
We only have 52 cards. So we can use the 64 bit integers as flag set.
This does that and makes deck follow the same api. As such this is a
breaking change to the deck struct.
It's recomended to use  CardBitSet whenever possible as it will be
faster and smaller.
Test Plan:
Lots of tests added

feat: add on `CardBitSet` for card sets

---

src/arena/agent/fn_observer.rs
src/arena/agent/mod.rs
src/arena/simulation.rs

Summary:
If we're going to have a CFR Agent then the agent needs to be able to
follow the game tree not just during it's own action, but also as other
actions are happening.
Test Plan:
Tests added
FnObserverRandomAgent is a good demonstration

feat: agents can be notified of actions as they happen

---

src/holdem/parse.rs

This fixes #77 
Not sure if having both functionalities in one function would be better.
Let me know if I should change anything 🙂 
Thanks for the great library!

Add a parse function to parse a comma separated list

---

src/arena/agent/calling.rs
src/arena/agent/folding.rs
src/arena/agent/random.rs
src/arena/historian/vec.rs
src/arena/sim_builder.rs
src/core/card.rs
src/core/card_bit_set.rs
src/core/card_iter.rs
src/core/deck.rs
src/core/hand.rs
src/holdem/monte_carlo_game.rs
src/holdem/parse.rs
src/holdem/starting_hand.rs

Summary:
Tests that use super::* are starting to give warnings.
Test Plan:
warnings are gone on build

fix: clear warnings about redundant use

---

src/arena/historian/fn_historian.rs
src/arena/historian/mod.rs
src/arena/historian/vec.rs
src/arena/mod.rs
src/arena/simulation.rs

Summary:
Historians are just watching the simulation. We should be able to drop some of them out.
Test Plan:
Use it in cfr and logging

feat: allow historians to fail

---

fuzz/fuzz_targets/multi_replay_agent.rs
fuzz/fuzz_targets/replay_agent.rs
src/arena/agent/random.rs
src/arena/game_state.rs
src/arena/simulation.rs

Summary:
This should help with optimization
Test Plan:
cargo test

refactor: don't use an optional for rounddata

---

src/arena/action.rs
src/arena/agent/random.rs
src/arena/errors.rs
src/arena/game_state.rs
src/arena/simulation.rs

I hope this helps. I assume the changes to the public interface are compatible with a 3.0.0 release, but of course I might be wrong.

Fix typo: ammount -> amount

---

benches/arena.rs
examples/agent_battle.rs
fuzz/Cargo.toml
fuzz/fuzz_targets/multi_replay_agent.rs
fuzz/fuzz_targets/replay_agent.rs
src/arena/action.rs
src/arena/agent/calling.rs
src/arena/agent/folding.rs
src/arena/agent/random.rs
src/arena/agent/replay.rs
src/arena/competition/generators.rs
src/arena/competition/sim_gen.rs
src/arena/game_state.rs
src/arena/historian/fn_historian.rs
src/arena/historian/vec.rs
src/arena/mod.rs
src/arena/sim_builder.rs
src/arena/simulation.rs

I experimented a bit with changes to GameState to support an ante in addition to the small blind and big blind. The approach in this pull request is to introduce a separate "Ante" round before "Starting" and "Preflop", which is admittedly quite intrusive and impacts a lot of code. Anyway, I am sharing it here in case it is of interest.
A separate commit adjusts the selection of the player first to act after each round (see #102).

Introduce an ante round before preflop

---

Cargo.lock
Cargo.toml
flake.lock

Summary:
- Update nix deps
- Update Cargo.toml
- Update Cargo.lock
Test Plan:
`cargo nextest run --all --all-targets`

chore: update deps

---

src/arena/action.rs
src/arena/agent/mod.rs
src/arena/agent/replay.rs
src/arena/game_state.rs
src/arena/historian/vec.rs
src/arena/sim_builder.rs
src/arena/simulation.rs

Summary:
When given a game state a simulation should always restart from the
exact same place. This fixes the issues where we were not living up to
that
- We would double blind
- We would not respect that the last player to act in a round might be
because we are restarting the simulation
This also splits the simulation up into a lot more rounds to make it
easier to see round changes as state changes in the game state.
Test Plan:
This was all found by the added test
Then the solution was further refined with fuzz testing

fix: allow simulations to restart from player actions

---

fuzz/fuzz_targets/multi_replay_agent.rs
src/arena/agent/random.rs
src/arena/agent/replay.rs
src/arena/game_state.rs
src/arena/simulation.rs
src/arena/test_util.rs
src/core/player_bit_set.rs

Summary:
Should we ask the next agent for an action or just skip everything is a
common question. This simplifes that by cleaning up the round active
logic to be explicit about who needs to act.
Test Plan:
Tests added
Fuzzing clean

fix: simplify betting continuation

---

fuzz/fuzz_targets/multi_replay_agent.rs

Summary:
Don't add a historian for everything unless we need it. This fixes the
perf
Test Plan:
Perf is back at 60k iterations

perf: multi replay agent perf improments

---

flake.nix

Summary:
On aarch64 there's no coverage targets. So don't try and generate packages that need the tools
Test Plan:
nix flake check on my mac laptop

fix: make llm cov package optional on osx

---

flake.nix

Summary:
To the nix flake add the cargo release command so I can release from any repo
Test Plan:
direnv reload

chore: add cargo-release

---

Cargo.lock
Cargo.toml

Summary:
beta.15 was released off a branch rather than master. So skip it
Test Plan:
Release master

chore: skip a version

---

fuzz/Cargo.toml

This cleans up a warning when building fuzz targets.

chore: add edition to fuzz Cargo.toml

---

flake.lock
flake.nix
src/arena/historian/directory_historian.rs
src/lib.rs

Summary:
Rust started using their own linker that blows up when in nix. So
rust-overlay wraps that linker with their own scripts. Fenix hasn't
found a fix yet.
I really want to get rid of gcc
Test Plan:
`cargo fuzz run multi_replay_agent -- -runs=1`

fix: fix fuzzing with 1.80 nightly

---

src/arena/competition/holdem_competition.rs
src/arena/game_state.rs

Summary:
When running a simulation we can transition from lots of different
rounds to complete via folding or via showdown. So keep track of what
the last round we have seen before complete'ing the sim.
Test Plan:
Ran `cargo run --release --example agent_battle`
Got:
```
Current Competition Stats: HoldemCompetition { num_rounds: 2500, total_change: [422.86856, -2458.051, 3308.6985, -1273.5121, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], max_change: [846.8667, 643.11194, 636.79913, 471.92227, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], min_change: [-641.6119, -835.31396, -411.79034, -774.67834, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], win_count: [975, 1111, 207, 212, 0, 0, 0, 0, 0, 0, 0, 0], zero_count: [273, 333, 1117, 1085, 0, 0, 0, 0, 0, 0, 0, 0], loss_count: [1252, 1056, 1176, 1203, 0, 0, 0, …
```

feat: keep track of the round before simlation completes

---

src/core/card_bit_set.rs
src/core/rank.rs

Summary:
There are some new cargo clippy fixes, apply these.
Test Plan:
- CI

style: cargo clippy --fix

---

src/arena/game_state.rs

Summary:
This allows creating a round that's in progress. Useful for simulations
that want to test calling all in or folds on later streets.
Test Plan:
- Doc tests
- Unit tests

feat: add `RoundData::new_with_bets` for in progress rounds

---

benches/rank.rs
fuzz/fuzz_targets/fuzzer_script_2.rs
fuzz/fuzz_targets/rank_seven.rs
src/arena/agent/random.rs
src/arena/game_state.rs
src/arena/sim_builder.rs
src/arena/simulation.rs
src/core/card_bit_set.rs
src/core/card_iter.rs
src/core/deck.rs
src/core/flat_hand.rs
src/core/hand.rs
src/core/mod.rs
src/core/rank.rs
src/holdem/monte_carlo_game.rs
src/holdem/parse.rs
src/holdem/starting_hand.rs

Summary:
- Move Deck to use CardBitSet
- Add FlatHand that allows indexing and ordering of cards  (it follow
FlatDeck's example)
- Add Hand that uses CardBitSet to do it's thing
- Move to using Hand and Deck in Simulation
Test Plan:
- CI
- Tests added

perf: use bitsets for deck and hands

---

.cargo/config.toml
Cargo.lock
Cargo.toml
fuzz/fuzz_targets/multi_replay_agent.rs
fuzz/fuzz_targets/replay_agent.rs
src/arena/cfr/action_generator.rs
src/arena/cfr/agent.rs
src/arena/cfr/historian.rs
src/arena/cfr/mod.rs
src/arena/cfr/node.rs
src/arena/cfr/state.rs
src/arena/game_state.rs
src/arena/mod.rs
src/arena/simulation.rs

This PR doesn't add all the code working yet. It adds the needed base `struct`s and `impl`s that will be needed. It gives the structure for adding CFR.

Add self playing CFR+ state and surrounding code

---

src/core/card_bit_set.rs

Summary:
Rather than per bit use the card iterator and the set formatting.
Test Plan:
/shrug

refactor: make the debug printing for card sets better

---

src/arena/cfr/mod.rs
src/core/card_bit_set.rs
src/core/hand.rs

Summary:
- Add CardBitSet & adn &=
- Add the same for hand
Test Plan:
- Tests added
- Use the BitAnd to compute the shared cards for boards

feat: add BitAnd and BitAnd BitAndAssign

---

src/arena/cfr/historian.rs
src/arena/cfr/node.rs

Summary:
Previously we when the historian created a node it used the default
playerdata to create the node. However the player idx needs to be
correctly set
Test Plan:
- Tests still pass

fix: add the player idx for playerdata via historians

---

src/arena/cfr/historian.rs

Summary:
The to_act_idx is changed by the time that historian is seeing. So use
the player idx from action payload.
Test Plan:
- CFR tests look better, but not fixed

fix: don't use player idx after the gamestate has changed

---

src/arena/cfr/agent.rs
src/arena/cfr/gamestate_iterator_gen.rs
src/arena/cfr/mod.rs

Rather than pass around how many to iterate, pass in the struct that will do that. This should allow for game state iterators taht change the starting hands of other players later.

refactor: pull CFRAgent gamestate iteration into a trait

---

src/arena/historian/fn_historian.rs
src/arena/sim_builder.rs

Summary:
- We are in a place where historians don't fail often so make the
default show that.
Test Plan:
- Tests Changed
- CI

refactor: panic by default if a historian fails

---

src/arena/cfr/agent.rs
src/arena/cfr/mod.rs

Summary:
- Previously we were keeping only the last one
- This should make the tests pass stabily
Test Plan:
- CI

fix: normalize reward over number of gamestates explored

---

examples/cfr_hand_demo.rs
src/arena/cfr/gamestate_iterator_gen.rs
src/arena/cfr/mod.rs

Summary:
- PerRoundFixedGameStateIteratorGen allows changing the number of
gamestates to explore. For the river we don't have any more cards to
come so fewer iterations are needed.
Test Plan:
- Perf got much better.

feat: add PerRoundFixedGameStateIteratorGen

---

Cargo.lock
Cargo.toml
src/arena/agent/all_in.rs
src/arena/agent/calling.rs
src/arena/agent/folding.rs
src/arena/agent/mod.rs
src/arena/agent/random.rs
src/arena/agent/replay.rs
src/arena/cfr/agent.rs
src/arena/cfr/historian.rs
src/arena/historian/directory_historian.rs
src/arena/historian/failing.rs
src/arena/historian/fn_historian.rs
src/arena/historian/mod.rs
src/arena/historian/null.rs
src/arena/historian/stats_tracking.rs
src/arena/historian/vec.rs
src/arena/sim_builder.rs
src/arena/simulation.rs

Summary:
Since I was looking at the flamegraph svg. I noticed a good ammount of
uuid time on cpu. We don't need that complexity. We only need an ID's
not going to repeat with no-coordination. This adds that by using u128
** This is a breaking change. **
It changes the Agent API
It changes the Historian API
Test:
hyperfine tests

perf: remove uuid

---

src/arena/cfr/agent.rs
src/arena/cfr/state.rs

Summary:
CFR State doesn't need that. So lets remove it.
Test Plan:
`cargo check`

refactor: remove un-used outputting

---

Cargo.lock
Cargo.toml
src/arena/cfr/agent.rs
src/arena/cfr/export.rs
src/arena/cfr/gamestate_iterator_gen.rs
src/arena/historian/stats_tracking.rs
src/arena/sim_builder.rs
src/arena/simulation.rs
src/arena/test_util.rs
src/core/card_iter.rs
src/core/flat_deck.rs
src/core/flat_hand.rs
src/simulated_icm/mod.rs

Summary:
- This allows agents to use the computed solution from before. Greatly
speeding up the process
- Added `CFRAgent.needs_to_explore()`
- Don't create the regret until needed.
- Use the presence of the regret matcher to keep track
- Up the number of games that the example uses as it's too fast for
timing now.
Test Plan:
- cargo test --all-features
- hyperfine

pref: don't re-explore nodes with enough games

---

fuzz/fuzz_targets/multi_replay_agent.rs
fuzz/fuzz_targets/replay_agent.rs

Summary:
- Change to the new api for sim builder in arena
- Use the mutable rng api for running the sim
Test Plan:
- cargo fuzz run replay_agent
- cargo fuzz run multi_replay_agent

fix: fuzzing wasn't updated when I changed HoldemSimulationBuilder

---

Cargo.lock
src/core/card.rs
src/core/card_bit_set.rs
src/core/deck.rs
src/core/flat_deck.rs
src/core/hand.rs

Summary:
- These were the most obviously missed tests that cargo mutants has
found.
- They include Card, Hand, FlatDeck, and Deck
Test Plan:
- These are the tests you were looking for.

test: add tests discovered by cargo mutants

---

.github/workflows/main.yml
.github/workflows/prod_compile.yml

Summary:
This PR moves cargo release compile into its own file so that runs in parallel with the test

build: split release compile into own workflow

---

Cargo.lock
Cargo.toml
examples/cfr_hand_demo.rs
src/arena/agent/mod.rs
src/arena/cfr/agent.rs
src/arena/cfr/mod.rs
src/arena/sim_builder.rs

Summary:
- Add `historian` method to `Agent`
- Change CFRAgent to handle this
- Bump Major Version
NOTE: This is a breaking change as you should not include CFR agents'
historians in your HoldemSimulationBuilder.
Test Plan:
- CI

refactor: allow agents to add their own historians in HoldemSimulationBuilder

---

fuzz/fuzz_targets/multi_replay_agent.rs

Summary:
When multiway pots are just the big blind then they have to be split. If
the big blind or folded small blind are so small that the division of
them breaks floating point then we are just testing the epsilon limits.
Test Plan:
- This doesn't break

test: keep fuzzing from hitting fp32 division issues with sb and bb

---

src/arena/action.rs
src/arena/agent/replay.rs
src/arena/cfr/action_generator.rs
src/arena/simulation.rs

Summary:
When an agent wants to call the current bet unconditionally they can now
pass the Call variant of the AgentAction enum. This will match the
current bet, putting them all in if the bet is larger than their stack
size.
Test Plan:
- Tests added

feat: add `AgentAction::Call` that calls the current bet

---

src/arena/cfr/action_generator.rs
src/arena/cfr/agent.rs
src/arena/cfr/export.rs
src/arena/cfr/state.rs
src/arena/cfr/state_store.rs
src/lib.rs

/claim #201
This PR makes `StateStore` and `CFRState` thread-safe by replacing `Rc<RefCell<>>` usage with `Arc<RwLock<>>`. Updated consumers of these classes to accept `RwLockReadGuard`/`RwLockWriteGuard` instead of `Ref`/`RefMut`. Updated documentation to reflect this.
Confirmation of the `Send + Sync` Auto Trait Implementations for `StateStore` and `CFRState` can be found in the automatically generated documentation under the "Auto Trait Implementations" section on the left.
Note: [`filter_map` for lock guards is a nightly-only experimental API](https://github.com/rust-lang/rust/issues/117108) requiring `#![feature(mapped_lock_guards)]` to be added to the crate features.

Make `StateStore` and `CFRState` `Send + Sync`
