elliottneilclark/rs-poker

.cargo/config
.gitignore
Cargo.toml
src/core/rank.rs
src/holdem/game.rs
src/holdem/game_bench.rs

* Only shuffle the deck when we are out of cards.
* Add on native profile by default. We are very reliant on popcnt
* Add a simple example program that will show how to use the simulation.

Vastly speed up game simulation

---

src/core/rank.rs

* Speed up rank_straight
* Speed up find_flush.
Suggestions per: https://www.reddit.com/r/rust/comments/64u4ns/performance_help_on_rspoker/dg543nd/

Speed up perf on Rankable

---

benches/game.rs

Fix the build after the rename.

Fix the build.

---

Cargo.toml
src/core/card.rs
src/core/flat_deck.rs

- Update rand to the newest version
- Fix removed sample module
- Fix usage of deprecated shuffle.

Update deps and clean new lints

---

.travis.yml
Cargo.toml
benches/game.rs
benches/holdem_starting_hand.rs
benches/iter.rs
benches/parse.rs
benches/rank.rs
src/core/card_iter.rs
src/core/deck.rs
src/core/flat_deck.rs
src/core/hand.rs
src/core/rank.rs
src/holdem/monte_carlo_game.rs
src/holdem/parse.rs
src/holdem/starting_hand.rs

Get rs-poker to the new edition

---

examples/game_simulate.rs
src/holdem/monte_carlo_game.rs

Greetings, thanks for this project! I've added support for board card in the monte carlo simulation. Is this something that you would like added into the project?

support board cards in simulation

---

Cargo.toml
benches/icm_sim.rs
src/arena/action.rs
src/arena/agent.rs
src/arena/errors.rs
src/arena/game_state.rs
src/arena/mod.rs
src/arena/simulation.rs
src/core/deck.rs
src/core/hand.rs
src/holdem/monte_carlo_game.rs
src/lib.rs
src/simulated_icm/mod.rs

In order to have a competitive arena there needs to be enough plumbing for a simulation. This adds a rough holdem simulation.

Prepare for an arena

---

src/arena/mod.rs
src/arena/random_nl_agent.rs
src/arena/simulation.rs

This pull request creates a new simple agent.

Add a random agent for No Limit Holdem

---

benches/monte_carlo_game.rs
examples/game_simulate.rs
src/arena/simulation.rs
src/core/hand.rs
src/holdem/monte_carlo_game.rs

Note this is a breaking change.

feat: allow unknown hole cards in monte carlo simulation

---

src/utils/player_bit_set.rs

- Doctests
- Documentation
- Better code docs

chore: add documentation for rs_poker::utils::PlayerBitSet

---

README.md
src/arena/action.rs
src/arena/agent/folding.rs
src/arena/simulation.rs

Summary:
Add documentation for `Agent`, `HoldemSimulation`, and `PlayerBitSet`
to the README.md preparing for a 2.0.0
Test Plan:
cargo fmt
ci

docs: readme for arena and new 2.0.0 features.

---

benches/arena.rs
src/arena/agent/random.rs

- Add a new method for RandomAgent
- Add a new set of benchmarks using this. The differences in timing help validate that things are behaving as expected.

feat: allow setting different chances in the random agents

---

src/arena/game_state.rs

test: add test describing the min raise for big blind

---

src/arena/simulation.rs
src/core/player_bit_set.rs

- Better display for PlayerSet
- Better documentation around folding for all the game state reasons

feat: make debugging arenas easier

---

.rustfmt.toml
src/arena/agent/mod.rs
src/arena/agent/random.rs
src/arena/game_state.rs
src/arena/simulation.rs
src/core/card.rs
src/core/deck.rs
src/core/hand.rs
src/core/player_bit_set.rs
src/core/rank.rs
src/holdem/mod.rs
src/holdem/parse.rs
src/lib.rs
src/simulated_icm/mod.rs

We didn't have a great intro that talked about all the different features.

docs: add an intro doc block for the crate

---

Cargo.lock
Cargo.toml
flake.lock
src/arena/action.rs
src/arena/agent/calling.rs
src/arena/agent/folding.rs
src/arena/agent/random.rs
src/arena/game_state.rs
src/arena/simulation.rs
src/core/card.rs
src/core/hand.rs
src/core/player_bit_set.rs
src/holdem/parse.rs
src/lib.rs

This adds an arena feature that's enabled by default. The arena feature also depends upon tracing.
This PR also adds instrumentation for each of the methods, and tracing events for most important changes in the game state.
This should close out most of the issues raised with #45

feat: add tracing to arena/simulation.

---

src/holdem/parse.rs

This solves #70.
In `RangeParse::parse_one`, if there is no modifier, calculate the gap in order to recognize a single pair, so that the range is built with `RangeIter::pair` instead of `RangeIter::stat`.
I'm not sure whether that's the best way to fix the issue.

fix: correctly parse ranges consisting of a single pair

---

Cargo.lock
Cargo.toml
flake.lock
flake.nix
src/arena/action.rs
src/arena/agent/replay.rs
src/arena/game_state.rs
src/arena/simulation.rs
src/core/rank.rs

Summary:
We should log when we give out money, and then the hand that got that.
Test Plan:
nix flake check

feat: add tracing/simulation for giving out cash

---

src/core/hand.rs

Fixes #78 
The deterministic test isn't the best, but maybe adding fuzzy testing is a bit overkill for this.

Make `Hand::new_from_str` deterministic

---

src/core/player_bit_set.rs

Summary:
It bugged me that this was so ugly.
Test Plan:
Tests don't make my eyes bleed.

fix: everything is zero based PlayerBitSet format should be too.

---

Cargo.lock
Cargo.toml
benches/arena.rs
examples/agent_battle.rs
flake.lock
fuzz/Cargo.toml
fuzz/fuzz_targets/multi_replay_agent.rs
src/arena/action.rs
src/arena/agent/calling.rs
src/arena/agent/folding.rs
src/arena/agent/random.rs
src/arena/agent/replay.rs
src/arena/competition/holdem_competition.rs
src/arena/competition/sim_gen.rs
src/arena/game_state.rs
src/arena/mod.rs
src/arena/simulation.rs
src/arena/test_util.rs
src/holdem/monte_carlo_game.rs

Summary:
f64 is enough bytes for me it will be enough bytes forever..... Until we
need more.
This also trims down GameState to only keep one RoundData at a time.
Test Plan:
Tests are clean
Fuzz runs for a while. Then finds a floating point issue.

refactor: change to single value type for arena

---

src/arena/action.rs
src/arena/simulation.rs

Summary:
Starting to get ready for CFR agent
Test Plan:
cargo check
cargo test
cargo fuzz replay agent

refactor: more instrumentation for simulation

---

Cargo.lock
Cargo.toml
src/arena/agent/fn_observer.rs
src/arena/agent/mod.rs
src/arena/historian/mod.rs
src/arena/historian/vec.rs
src/arena/mod.rs
src/arena/simulation.rs

Summary:
Rather than making everyone always record actions in a vec, let's make that configurable.
Test Plan:
- perf wins of about 3 to 5% single-threaded.

feat: allow configurable history

---

src/arena/agent/calling.rs
src/arena/historian/vec.rs
src/arena/mod.rs
src/lib.rs

- **docs: improve arena documentation**

Arena docs

---

src/core/card.rs
src/holdem/parse.rs

Summary:
These are always available.
Test Plan:
cargo release doesn't error out.

chore: clean build commands about duplicate imports

---

src/arena/action.rs
src/arena/game_state.rs
src/arena/historian/vec.rs
src/arena/simulation.rs

Summary:
This allows easier handling of the resulting actions in historians
Test Plan:
Used in cfr

refactor: unify FailedActionPayload

---

src/arena/historian/fn_historian.rs

Summary:
- Add a test that shows simulations don't stop
Test Plan:
- Test added

test: add test for returning errors from historian

---

fuzz/fuzz_targets/multi_replay_agent.rs
src/arena/agent/replay.rs
src/arena/game_state.rs
src/arena/historian/vec.rs
src/arena/simulation.rs

Summary:
- Some floating point issues with very small number with ante's. So punt
on them for now an require input that's reasonable.
- Found an issue with player going all in early rounds causing agents to
still act later.
Test Plan:
- Tests Pass
- Fuzzing examples pass

fix: fix fuzzing for longer

---

src/arena/agent/failing.rs
src/arena/agent/mod.rs
src/arena/agent/replay.rs
src/arena/historian/vec.rs
src/arena/sim_builder.rs
src/arena/simulation.rs

Summary:
Chasing down why cfr is broken this could be helpful.
Test Plan:
Added tests

feat: add the abiltty to choose to panic on failing historian

---

Cargo.lock
Cargo.toml
flake.lock

Summary:
Update all the deps
Test Plan:
cargo test
cargo nextest run
cargo clippy

chore(deps): update versions of nix and cargo

---

src/arena/competition/tournament.rs
src/arena/mod.rs

Summary:
Give a more informative result
Test Plan:
Cargo test
Docs added

refactor: change the return type of SingleTableTournament.run

---

src/arena/action.rs
src/arena/competition/holdem_competition.rs
src/arena/simulation.rs
src/core/card.rs
src/core/card_bit_set.rs
src/core/deck.rs
src/core/error.rs
src/holdem/monte_carlo_game.rs
src/lib.rs
src/simulated_icm/mod.rs

Summary:
- Some unit tests
- More examples
- Document functions that should be called by users
Test Plan:
cargo check
cargo test

docs: more docs on newer code

---

.gitignore
Cargo.lock
Cargo.toml
examples/agent_battle.rs
src/arena/action.rs
src/arena/agent/calling.rs
src/arena/game_state.rs
src/arena/historian/directory_historian.rs
src/arena/historian/mod.rs
src/core/player_bit_set.rs

Summary:
- Add a `DirectoryHistorian`
- Use that in exmple AgentBattle
Test Plan:
Ran agent_battle example

feat: add historian that writes json to a directory

---

Cargo.lock
Cargo.toml
flake.lock
flake.nix

Summary:
- Update nix deps
- Upate Cargo.toml deps
- Update Cargo.lock deps
- Add some cargo utility deps to the dev shell
Test Plan:
ci
cargo nextest

chore: update lot of deps

---

benches/arena.rs
examples/agent_tournament.rs
src/arena/agent/calling.rs
src/arena/agent/folding.rs
src/arena/agent/random.rs
src/arena/agent/replay.rs
src/arena/competition/holdem_competition.rs
src/arena/competition/sim_gen.rs
src/arena/competition/tournament.rs
src/arena/game_state.rs
src/arena/historian/failing.rs
src/arena/historian/fn_historian.rs
src/arena/historian/mod.rs
src/arena/historian/vec.rs
src/arena/mod.rs
src/arena/sim_builder.rs
src/lib.rs

Summary:
The changes needed to make starting an arena in the middle of a round.
Test Plan:
- Tests changed

feat: allow starting a simulation on different round gamestate

---

Cargo.lock
Cargo.toml

Summary:
- Bump everything
Test Plan:
- CI

chore: update all the deps

---

Cargo.lock
Cargo.toml

Summary:
Bump deps
Test Plan:
CI

chore: update serde_json

---

Cargo.lock
Cargo.toml
benches/icm_sim.rs
fuzz/Cargo.toml
src/arena/agent/calling.rs
src/arena/agent/random.rs
src/arena/competition/sim_gen.rs
src/arena/game_state.rs
src/arena/sim_builder.rs
src/core/flat_deck.rs
src/holdem/monte_carlo_game.rs
src/lib.rs
src/simulated_icm/mod.rs

Summary:
New fat rng dropped. Gotta get it
Test Plan:
- Fuzz replay_agent
- cargo check
- cargo test
- ci

chore: update rng

---

.github/workflows/main.yml

Summary:
- Permissions
- Don't persist
Test Plan:
- CI

build: lock down gh a little bit more

---

fuzz/fuzz_targets/multi_replay_agent.rs
src/arena/agent/replay.rs
src/arena/test_util.rs

Summary:
This makes fuzzing go forever
Test Plan:
Fuzz for longer now

fix: make test_util take into account 0 sb + bb

---

src/arena/cfr/mod.rs

Summary:
It's not allways the same round....
Test Plan:
More tests pass than ever before.

fix: test fix for heads up should fold 72 offsuit

---

Cargo.lock
Cargo.toml
benches/arena.rs
benches/icm_sim.rs
examples/agent_battle.rs
examples/agent_tournament.rs
src/arena/agent/all_in.rs
src/arena/agent/folding.rs
src/arena/agent/random.rs
src/arena/agent/replay.rs
src/arena/cfr/action_generator.rs
src/arena/cfr/agent.rs
src/arena/cfr/mod.rs
src/arena/competition/holdem_competition.rs
src/arena/competition/sim_gen.rs
src/arena/competition/tournament.rs
src/arena/game_state.rs
src/arena/historian/failing.rs
src/arena/historian/fn_historian.rs
src/arena/historian/mod.rs
src/arena/historian/vec.rs
src/arena/mod.rs
src/arena/sim_builder.rs
src/arena/simulation.rs
src/arena/test_util.rs
src/core/flat_deck.rs
src/holdem/parse.rs
src/lib.rs
src/simulated_icm/mod.rs

Summary:
- Migrate edition
- rename a few places that had `gen` keyword
Test Plan:
- CI
- cargo test passes

chore: migrate edition

---

src/arena/cfr/agent.rs

Summary:
These show earlier that we are always pointing at a chance node when the
tree expects a player. This should help
Test Plan:
- Getting closer

test: add more assertions

---

src/arena/cfr/state.rs

Summary:
- Rust docs all the things
Test Plan:
- Docs are tested in ci

docs: add CFRState docs

---

Cargo.lock
Cargo.toml
src/arena/cfr/action_generator.rs
src/lib.rs

Summary:
little sorry is updated to allow use of 0.9.0 so, lets update here
Test Plan:
- CI

chore: update little-sorry to use new rand

---

examples/agent_battle.rs
src/arena/competition/holdem_competition.rs
src/arena/competition/mod.rs
src/arena/competition/sim_iterator.rs
src/arena/game_state.rs
src/arena/mod.rs
src/lib.rs

Summary:
- Gamestate iterators
- Simulation iterators
Test Plan:
- Tests still pass

refactor: better usage of iterators

---

examples/cfr_export_demo.rs
src/arena/cfr/agent.rs
src/arena/cfr/export.rs
src/arena/cfr/node.rs
src/arena/cfr/state.rs

Summary:
- ensure that the player idx matches
- ensure that the number of cards makes sense
Test Plan:
- Assertions added still pass

fix: add player_idx to CFR player data

---

src/arena/historian/mod.rs
src/arena/historian/stats_tracking.rs
src/arena/historian/vec.rs
src/core/rank.rs

Summary:
- Add a StatTrackingHistorian
- Add StatsStorage for all the counts
- Make VecHistorian follow the same pattern. It can return the ref counted storage inner.
Test:
- Disabled test included.

feat: add new stat tracking historian.

---

src/arena/cfr/mod.rs

Explore more when doing the should fold methods

test: make arena cfr tests more stable

---

src/arena/cfr/mod.rs

Summary:
- Don't allow any way for there to be a flush that player 1 can be the
highest
Test Plan:
- CI

test: try and make test_should_fold_after_preflop stable

---

Cargo.toml
benches/arena.rs
benches/deal_deck.rs
examples/cfr_hand_demo.rs
src/arena/agent/calling.rs
src/arena/agent/folding.rs
src/arena/agent/random.rs
src/arena/agent/replay.rs
src/arena/cfr/agent.rs
src/arena/cfr/mod.rs
src/arena/competition/holdem_competition.rs
src/arena/competition/sim_iterator.rs
src/arena/competition/tournament.rs
src/arena/game_state.rs
src/arena/historian/failing.rs
src/arena/historian/fn_historian.rs
src/arena/historian/stats_tracking.rs
src/arena/historian/vec.rs
src/arena/mod.rs
src/arena/sim_builder.rs
src/arena/simulation.rs
src/core/card_bit_set.rs
src/core/deck.rs
src/core/hand.rs

- **feat: add ability to sample and deal from Deck**
- **perf: use fewer allocations in arena**

Optimize Arena/HoldemSimulationBuilder

---

src/arena/cfr/agent.rs
src/arena/cfr/historian.rs
src/arena/game_state.rs

Summary:
Utility is the change in stack for us. So use that everywhere
Test Plan:
Ran the example

fix: use the same reward in CFR Tree as in CFR Agent

---

src/arena/game_state.rs
src/arena/simulation.rs
src/arena/test_util.rs

Summary:
- Fewer mallocs
Test Plan:
- compare demo times

perf: optimize gamestate removing some of the stats vec's

---

Cargo.lock
Cargo.toml
examples/cfr_hand_demo.rs

Summary:
- No more malloc/free in perf
Test Plan:
- hyperfine

perf: use jemalloc on cfr_hand_demo example

---

Cargo.toml

Summary:
We're jemalloc on all dev things.
Test Plan:
- no more yelling at me please. I'm sensitive

fix: remove unused feature in example

---

Cargo.lock
Cargo.toml
examples/cfr_hand_demo.rs

Summary:
- This seems better maintained
Test Plan:
- Perf?

chore(deps): update to a newer jemalloc rust crate

---

Cargo.lock
Cargo.toml

Summary:
- Update to 1.1.0
Test Plan:
- CI

chore: update little-sorry

---

.gitignore

Summary:
cargo mutants is interesting. So ignore the output if it's run
Test Plan:
/shrug

chore: ignore mutants

---

examples/cfr_hand_demo.rs

This adds the conditional annotation on jemalloc usage in demo

fix: allow compiling without jemalloc

---

src/core/card.rs

Summary:
Add another test found by cargo mutants
Test:
Added a test

test: add Value::to_char test

---

examples/agent_battle.rs
examples/agent_tournament.rs
examples/cfr_export_demo.rs
examples/cfr_hand_demo.rs
examples/game_simulate.rs
src/arena/cfr/agent.rs
src/arena/cfr/export.rs
src/arena/cfr/state_store.rs
src/arena/test_util.rs
src/core/card_bit_set.rs
src/core/player_bit_set.rs

Summary:
cargo clippy --fix --all --all-targets
Test Plan:
CI

fix: cargo clippy with nightly to pass formatting checks

---

README.md
src/lib.rs

Summary:
- Add more around docs
- Make it sound more fun
Test Plan:
- CI

docs: add more docs around arena

---

src/arena/agent/random.rs

Summary:
I added the Call action a little bit ago, however the RandomAgent wasn't using it. So this commit changes that
Test:
The RandomAgent is already well tested.

refactor: use Action::Call in RandomAgent

---

Cargo.lock
Cargo.toml
fuzz/Cargo.toml
src/arena/cfr/action_generator.rs
src/arena/cfr/agent.rs
src/arena/cfr/state.rs
src/core/card.rs
src/core/card_iter.rs
src/core/flat_hand.rs
src/lib.rs
src/open_hand_history/hand_history.rs
src/open_hand_history/mod.rs
src/open_hand_history/serde_utils.rs
src/open_hand_history/writer.rs

Summary:
- Add decoding for open hand history
- add writing to a file
Test Plan:
- tests included

feat: add open hand history module
